// Import createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Define the shape of the AuthState
interface AuthState {
  isLoggedIn: boolean; // Indicates whether the user is logged in or not
}

// Retrieve the token from localStorage
const token = localStorage.getItem('token');

// Define the initial state based on the presence of a token
const initialState: AuthState = {
  isLoggedIn: token !== null && token !== undefined, // User is considered logged in if a token is present
};

// Create a Redux slice named 'auth'
const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    // Reducer to handle a successful login
    loginSuccess(state) {
      state.isLoggedIn = true; // Set isLoggedIn to true upon successful login
    },
    // Reducer to handle a logout
    logout(state) {
      localStorage.removeItem('token'); // Remove token from localStorage on logout
      localStorage.removeItem('id'); // Remove user id from localStorage on logout
      state.isLoggedIn = false; // Set isLoggedIn to false on logout
    },
  },
});

// Extract the action creators generated by createSlice
export const { loginSuccess, logout } = authSlice.actions;

// Export the reducer generated by createSlice
export default authSlice.reducer;
